### ISSUE TITLE
如何修改商品信息中图片上传尺寸大小限制？

### ISSUE THREAD

**Issue by DongyuWutong** [jishenghua/jshERP#102]
目前的设备采集照片分辨率都很高了，1M的限制会导致采集的照片需要经过二次处理才能上传。

**Comment by jishenghua** [comment]
这个可以通过修改代码解决的呀，默认是10M呀，考虑到流量的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月15日(星期一) 下午4:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [jishenghua/jshERP] 如何修改商品信息中图片上传尺寸大小限制？ (Issue #102)














 
目前的设备采集照片分辨率都很高了，1M的限制会导致采集的照片需要经过二次处理才能上传。

**Comment by DongyuWutong** [comment]
> 这个可以通过修改代码解决的呀，默认是10M呀，考虑到流量的问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年4月15日(星期一) 下午4:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [jishenghua/jshERP] 如何修改商品信息中图片上传尺寸大小限制？ (Issue #102) 目前的设备采集照片分辨率都很高了，1M的限制会导致采集的照片需要经过二次处理才能上传。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

前端页面上传的时候有提示限制图片大小1M的，大于1M的图片会上传失败。
然后请问，如果修改的话是通过修改如下配置实现吗？
spring.servlet.multipart.max-file-size=10485760
spring.servlet.multipart.max-request-size=10485760

**Comment by DongyuWutong** [comment]
可以通过修改配置文件调整上传图片大小。
