### ISSUE TITLE
部分中文乱码

### ISSUE THREAD

**Issue by jiuyuan-light** [jishenghua/jshERP#108]
### 部分中文乱码
![g1](https://github.com/jishenghua/jshERP/assets/89025318/dd125aa5-9260-480c-afc2-3239bc03cdc8)

### 在如下虚拟环境部署，jar从`https://share.weiyun.com/NDJNLhry`下载。
```
root@3d1d03271da8:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"  
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/" 
```
有人知道这是啥问题吗

**Comment by jishenghua** [comment]
应该是和数据库里面的字符编码格式有关




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月10日(星期一) 晚上7:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [jishenghua/jshERP] 部分中文乱码 (Issue #108)














 
部分中文乱码
 
g1.jpg (view on web)
 
在如下虚拟环境部署，jar从https://share.weiyun.com/NDJNLhry下载。
 ***@***.***:~# cat /etc/os-release  PRETTY_NAME="Debian GNU/Linux 10 (buster)"   NAME="Debian GNU/Linux" VERSION_ID="10" VERSION="10 (buster)" VERSION_CODENAME=buster ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"   
有人知道这是啥问题吗

**Comment by jiuyuan-light** [comment]
哦，改了数据库编码为utf-8，重建了数据库就好了。
