### ISSUE TITLE
支持英文版吗？

### ISSUE THREAD

**Issue by ggh0604** [jishenghua/jshERP#110]
如题，支持多语言切换吗？

**Comment by jishenghua** [comment]
不支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月3日(周三) 上午10:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jishenghua/jshERP] 支持英文版吗？ (Issue #110)




 
如题，支持多语言切换吗？

**Comment by jishenghua** [comment]
目前不支持



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月1日(星期四) 上午10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jishenghua/jshERP] 支持英文版吗？ (Issue #110)














 
Closed #110 as completed.
