### ISSUE TITLE
为什么BOM不是取SKU表

### ISSUE THREAD

**Issue by yanmingh** [jishenghua/jshERP#114]
想请教一下作者关于系统设计的问题，为什么BOM管理中左侧不是获取SKU的表，而是获取商品的表？
会出现一个情况就是，我想要配置某个商品下面的一个规格，但是在BOM左侧位置不可以选择
![Snipaste_2024-10-23_15-47-33](https://github.com/user-attachments/assets/cb16ee7d-652f-4c21-8dbe-98b593e0c6e8)

**Comment by jishenghua** [comment]
那样需要设置太多的BOM了，比较麻烦的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月23日(周三) 下午3:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jishenghua/jshERP] 为什么BOM不是取SKU表 (Issue #114)




 
想请教一下作者关于系统设计的问题，为什么BOM管理中左侧不是获取SKU的表，而是获取商品的表？
 会出现一个情况就是，我想要配置某个商品下面的一个规格，但是在BOM左侧位置不可以选择
 Snipaste_2024-10-23_15-47-33.png (view on web)
