### ISSUE TITLE
gitee版本

### ISSUE THREAD

**Issue by blossom-x** [jishenghua/jshERP#13]
这里这个和gitee上的华夏ERP是同一个把？为什么两边的版本号不太一致？

**Comment by jishenghua** [comment]
是同一个，这边更新稍微慢几天




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jishenghua/jshERP"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月15日(星期二) 晚上11:24
收件人:&nbsp;"jishenghua/jshERP"<jshERP@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jishenghua/jshERP] gitee版本 (#13)





 
这里这个和gitee上的华夏ERP是同一个把？为什么两边的版本号不太一致？

**Comment by blossom-x** [comment]
欧克，感谢开源
