### ISSUE TITLE
单据编辑的其他费用可以在多行选择相同的费用项目，此时如果输入了不同的金额，保存再打开就变成相同的金额

### ISSUE THREAD

**Issue by No5972** [jishenghua/jshERP#18]
所有有优惠金额编辑选项的单据编辑界面的其他费用可以在多行选择相同的费用项目。
此时如果输入了不同的金额，保存再打开就变成相同的金额。
然后再将其他费用逐一取消，将所有条目取消之后最后合计不为零，可能是正数也可能是负数。
编辑前：
![](https://s1.ax1x.com/2020/10/13/0h80IO.png)
编辑后：
![](https://s1.ax1x.com/2020/10/13/0h8DiD.png)
然后逐一取消：
![](https://s1.ax1x.com/2020/10/13/0h8rJe.png)

**Comment by jishenghua** [comment]
这个版本目前已经停止更新了，请用vue版本
