### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by chengupc** [jishenghua/jshERP#28]
后台报错 
2021/08/17-10:56:56 ERROR [http-nio-9999-exec-4] com.jsh.erp.controller.UserController - Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisDataException: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct

**Comment by jishenghua** [comment]
这个报错代表redis连接失败了，检查下配置看看
