### ISSUE TITLE
库存统计没有区分sku多属性

### ISSUE THREAD

**Issue by BerryLong** [jishenghua/jshERP#38]
商品库存统计没有支持sku多属性商品，例如商品A有两个颜色（白色、黑色），白色库存为0，黑色库存为1，这是个即使是关闭负库存，新增单据用白色商品也会成功，这里是否新增sku逻辑

**Comment by jishenghua** [comment]
好的，我排查下

**Comment by jishenghua** [comment]
已经修改完成
