### ISSUE TITLE
要开源你就好好做，想搞钱tm做好点收费，又不给完整的文档，出现问题门票20，这问题是不是你自己留的都不确定，还有什么用户限制另外付费，秀

### ISSUE THREAD

**Issue by linshaoSec** [jishenghua/jshERP#47]

**Comment by jishenghua** [comment]
你就是个脑残，死去吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月22日(周五) 中午12:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jishenghua/jshERP] 要开源你就好好做，想搞钱tm做好点收费，又不给完整的文档，出现问题门票20，这问题是不是你自己留的都不确定，还有什么用户限制另外付费，秀 (Issue #47)

**Comment by jishenghua** [comment]
垃圾评论

**Comment by jishenghua** [comment]
小黑粉，没素质
