### ISSUE TITLE
过滤器有绕过

### ISSUE THREAD

**Issue by Ba3s** [jishenghua/jshERP#49]
老哥你这filter用contains来判断的话，这个容易出大事啊

**Comment by jishenghua** [comment]
还好吧，不会出大问题

**Comment by Ba3s** [comment]
![image](https://user-images.githubusercontent.com/60291208/166890612-9c1e84c6-9832-4707-a57a-2d3f6b896564.png)
这不就绕了，未授权直接访问后台了
