### ISSUE TITLE
组件中文乱码

### ISSUE THREAD

**Issue by kityang** [jishenghua/jshERP#7]
如图。不知是什么原因。
<img width="369" alt="截屏2020-04-16下午2 34 44" src="https://user-images.githubusercontent.com/8792898/79422547-ad528880-7fef-11ea-8e79-19bdc439422d.png">

**Comment by kityang** [comment]
数据库内容正常，取出来传到前端就乱码了

**Comment by ly020044** [comment]
我也遇到了这个问题，你怎么解决的？
