### ISSUE TITLE
报表查询的商品库存页面接口获取数据失败，且项目已更新至最新

### ISSUE THREAD

**Issue by ahh556** [jishenghua/jshERP#78]
mysql版本为5.7.40
报错为org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'jsh_erp.me.commodity_unit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'jsh_erp.me.commodity_unit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by jishenghua** [comment]
需要改MySQL的自身配置，支持group by分组的多返回字段的方式



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月15日(周三) 晚上8:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jishenghua/jshERP] 报表查询的商品库存页面接口获取数据失败，且项目已更新至最新 (Issue #78)




 
mysql版本为5.7.40
 报错为org.springframework.jdbc.BadSqlGrammarException:
 
Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'jsh_erp.me.commodity_unit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
 
The error may exist in file [F:\IdeaProjects\jxc\jshERP\jshERP-boot\target\classes\mapper_xml\MaterialMapperEx.xml]
 
The error may involve defaultParameterMap
 
The error occurred while setting parameters
 
SQL: SELECT m.*, me.commodity_unit unitName, mc.name categoryName, me.bar_code, ifnull(me.purchase_decimal, 0) purchase_decimal, ifnull(sum(mcs.current_number), 0) currentStock, sum(ifnull(me.purchase_decimal, 0) * ifnull(mcs.current_number, 0)) currentStockPrice FROM jsh_material m LEFT JOIN jsh_material_extend me ON me.tenant_id = 63 AND m.id = me.material_id AND ifnull(me.delete_Flag, '0') != '1' LEFT JOIN jsh_material_current_stock mcs ON mcs.tenant_id = 63 AND m.id = mcs.material_id AND ifnull(mcs.delete_flag, '0') != '1' LEFT JOIN jsh_unit u ON u.tenant_id = 63 AND m.unit_id = u.id AND ifnull(u.delete_Flag, '0') != '1' LEFT JOIN jsh_material_category mc ON mc.tenant_id = 63 AND m.category_id = mc.id AND ifnull(mc.delete_Flag, '0') != '1' WHERE m.tenant_id = 63 AND 1 = 1 AND me.default_flag = 1 AND mcs.depot_id IN (?, ?, ?) AND ifnull(m.delete_flag, '0') != '1' GROUP BY m.id ORDER BY m.id DESC LIMIT ?, ?
 
Cause: java.sql.SQLSyntaxErrorException: Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'jsh_erp.me.commodity_unit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
 
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'jsh_erp.me.commodity_unit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by ahh556** [comment]
> 需要改MySQL的自身配置，支持group by分组的多返回字段的方式
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月15日(周三) 晚上8:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [jishenghua/jshERP] 报表查询的商品库存页面接口获取数据失败，且项目已更新至最新 (Issue #78) mysql版本为5.7.40 报错为org.springframework.jdbc.BadSqlGrammarException: Error querying database. Cause: java.sql.SQLSyntaxErrorException: Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'jsh_erp.me.commodity_unit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by The error may exist in file [F:\IdeaProjects\jxc\jshERP\jshERP-boot\target\classes\mapper_xml\MaterialMapperEx.xml] The error may involve defaultParameterMap The error occurred while setting parameters SQL: SELECT m.*, me.commodity_unit unitName, mc.name categoryName, me.bar_code, ifnull(me.purchase_decimal, 0) purchase_decimal, ifnull(sum(mcs.current_number), 0) currentStock, sum(ifnull(me.purchase_decimal, 0) * ifnull(mcs.current_number, 0)) currentStockPrice FROM jsh_material m LEFT JOIN jsh_material_extend me ON me.tenant_id = 63 AND m.id = me.material_id AND ifnull(me.delete_Flag, '0') != '1' LEFT JOIN jsh_material_current_stock mcs ON mcs.tenant_id = 63 AND m.id = mcs.material_id AND ifnull(mcs.delete_flag, '0') != '1' LEFT JOIN jsh_unit u ON u.tenant_id = 63 AND m.unit_id = u.id AND ifnull(u.delete_Flag, '0') != '1' LEFT JOIN jsh_material_category mc ON mc.tenant_id = 63 AND m.category_id = mc.id AND ifnull(mc.delete_Flag, '0') != '1' WHERE m.tenant_id = 63 AND 1 = 1 AND me.default_flag = 1 AND mcs.depot_id IN (?, ?, ?) AND ifnull(m.delete_flag, '0') != '1' GROUP BY m.id ORDER BY m.id DESC LIMIT ?, ? Cause: java.sql.SQLSyntaxErrorException: Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'jsh_erp.me.commodity_unit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Expression #22 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'jsh_erp.me.commodity_unit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

设置模式之后解决了，谢谢啦，不过返回列表最后的总共库存的数量带了小数点。
