### ISSUE TITLE
we

### ISSUE THREAD

**Issue by haha3232** [jishenghua/jshERP#87]
库存更新为什么要查所有订单,就是为了保证数据准确性吗

一个简单的账户流水, 为什么不建一个流水表来记录,  非要 jsh_depot_head 和 jsh_account_head  
**
![image](https://user-images.githubusercontent.com/127198845/233565739-22232257-9a11-4b8f-b1d4-52b5687fe10c.png)
**
![image](https://user-images.githubusercontent.com/127198845/233565603-d4c7e3d9-8a24-4d63-9133-20a199ee4585.png)
不理解为什么这么写代码, 不在sql 里面, 真是 不良代码规范

**Comment by jishenghua** [comment]
不通过查询，如果程序出bug了，流水就全都错了，到时候修复起来很麻烦的。库存也是这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月21日(星期五) 下午3:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [jishenghua/jshERP] we (Issue #87)





 
库存更新为什么要查所有订单,就是为了保证数据准确性吗
 
一个简单的账户流水, 为什么不建一个流水表来记录,  非要 jsh_depot_head 和 jsh_account_head
 **
 
 **
 
 不理解为什么这么写代码, 不在sql 里面, 真是 不良代码规范

**Comment by haha3232** [comment]
代码业务功底,真的不敢恭维, 代码逻辑各种接口混乱不堪

**Comment by haha3232** [comment]
很多地方都是为了省掉单独表,公用一张表,太难理解代码逻辑啦

**Comment by jishenghua** [comment]
表多了的话，你查起来会更加复杂




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月21日(星期五) 下午3:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jishenghua/jshERP] we (Issue #87)





 
很多地方都是为了省掉单独表,公用一张表,太难理解代码逻辑啦

**Comment by haha3232** [comment]
> 不通过查询，如果程序出bug了，流水就全都错了，到时候修复起来很麻烦的。库存也是

现在库存有个bug,  采购入库, 未通过审核的单据,  也会计算到当前库存里面去

**Comment by haha3232** [comment]
后面如果再加几种订单状态, 更新库存这里的sql 都要去注意看是不是需要改动, 
还有查询流水这里的sql也是要看是否要改动,否则就会出现现在, 未审核的单据也出现在商品 库存流水中, 

如果额外表, 和单独加减库存, 就能和 单据数据耦合开, 逻辑没有强关联性

**Comment by haha3232** [comment]
账户流水记录也把未审核的单据统计进来了

**Comment by jishenghua** [comment]
默认是会统计的，你可以在系统配置里面开启强审核



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月22日(星期六) 上午10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jishenghua/jshERP] we (Issue #87)





 
账户流水记录也把未审核的单据统计进来了

**Comment by haha3232** [comment]
首页统计金额  一个销售单 两个商品， 会计算两倍
