### ISSUE TITLE
前端页面太丑

### ISSUE THREAD

**Issue by Captain-Justin** [jishenghua/jshERP#9]
找个UI和前端吧，这画风10年前了。

**Comment by jishenghua** [comment]
个人开源项目，找不起UI，后面会尽量优化

**Comment by No5972** [comment]
easyui 有个好处，兼容旧版IE浏览器（6+）。只要Jquery换成低版本的就可以。

国内的很多企业环境特别是制造业很多电脑还是比较老旧的有些甚至还是XP系统，很多也不愿意使用IE以外的浏览器。有很多时候甲方明确要求要能在IE浏览器使用。这反倒造就了easyui 的优势。😂
