### ISSUE TITLE
按钮权限问题

### ISSUE THREAD

**Issue by guohh18** [jishenghua/jshERP#91]
部署服务后，使用jsh账号访问，只有查看数据的权限，各种新增修改按钮都没有，数据库jsh_user_business表的btn_str都是空的，使用注册功能新注册的号也是只有查看权限，这个权限要在哪里配置啊，看了后端的注册接口registerUser，插入表数据时也没有看到设置btnStr

![image](https://github.com/jishenghua/jshERP/assets/115476780/5faaa050-fe55-42dc-9aba-cb1e2e18c69d)
![image](https://github.com/jishenghua/jshERP/assets/115476780/5952e01d-81ea-419d-a08b-ecd219549cae)

**Comment by guohh18** [comment]
![image](https://github.com/jishenghua/jshERP/assets/115476780/a9eb5954-7da3-4449-8d1f-01472cc60521)

没有新增按钮，批量操作下拉选项也是空的

**Comment by jishenghua** [comment]
是不是部署的地址挂在二级目录了呀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月20日(周二) 下午4:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jishenghua/jshERP] 按钮权限问题 (Issue #91)




 
部署服务后，使用jsh账号访问，只有查看数据的权限，各种新增修改按钮都没有，数据库jsh_user_business表的btn_str都是空的，使用注册功能新注册的号也是只有查看权限，这个权限要在哪里配置啊，看了后端的注册接口registerUser，插入表数据时也没有看到设置btnStr

**Comment by guohh18** [comment]
> 

因为我的服务器上部署了很多自己练手的乱七八糟小项目，怕冲突就把这个项目打成镜像部署到Docker里了，这个按钮权限和部署位置有关吗，我看登录接口代码，是读取的jsh_user_business表数据，但是没找到插入数据的地方

**Comment by jishenghua** [comment]
没试过docker部署，可能会有问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月22日(周四) 中午12:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jishenghua/jshERP] 按钮权限问题 (Issue #91)




   
因为我的服务器上部署了很多自己练手的乱七八糟小项目，怕冲突就把这个项目打成镜像部署到Docker里了，这个按钮权限和部署位置有关吗，我看登录接口代码，是读取的jsh_user_business表数据，但是没找到插入数据的地方

**Comment by guohh18** [comment]
已解决，问题原因是我在主机上的nginx通过/erp代理请求到容器的nginx，URL多了一个/erp，判断当前页面权限的那段代码里会根据当前页面的URL和接口返回的的对比，不一致就有问题，判断前把/erp截取掉就好了。
![image](https://github.com/jishenghua/jshERP/assets/115476780/3962bb93-6370-4a69-9b07-ce500071d657)
